from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *


class Ui_Dialog(object):
    def __init__(self):
        self.result = 0

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(831, 582)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-160, 510, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 59, 670, 441))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(700, 60, 81, 451))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_2)
        self.comboBox_4 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_4)
        self.comboBox_5 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_5)
        self.comboBox_6 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_6)
        self.comboBox_8 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_8)
        self.comboBox_10 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_10)
        self.comboBox_13 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_13)
        self.comboBox_12 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_12)
        self.comboBox_9 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_9)
        self.comboBox_14 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_14)
        self.comboBox_11 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_11)
        self.comboBox_7 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_7)
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_3)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def calculate_vaf(self):
        self.total_VAF = 0
        self.total_VAF += int(self.comboBox.currentText())
        self.total_VAF += int(self.comboBox_2.currentText())
        self.total_VAF += int(self.comboBox_3.currentText())
        self.total_VAF += int(self.comboBox_4.currentText())
        self.total_VAF += int(self.comboBox_5.currentText())
        self.total_VAF += int(self.comboBox_6.currentText())
        self.total_VAF += int(self.comboBox_7.currentText())
        self.total_VAF += int(self.comboBox_8.currentText())
        self.total_VAF += int(self.comboBox_9.currentText())
        self.total_VAF += int(self.comboBox_10.currentText())
        self.total_VAF += int(self.comboBox_11.currentText())
        self.total_VAF += int(self.comboBox_12.currentText())
        self.total_VAF += int(self.comboBox_13.currentText())
        self.total_VAF += int(self.comboBox_14.currentText())

        self.set_vaf_value(self.total_VAF)

    def set_vaf_value(self, value):
        self.result = value

    def get_vaf_value(self):
        return self.result

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Value Adjustment Factors"))
        Dialog.setWindowIcon(QtGui.QIcon(r"C:\Users\rosha\PycharmProjects\FunctionPointGUIprogram\Static"
                                             r"\metrics.png"))
        self.label.setText(
            _translate("Dialog", "Assign a value from 0 to 5 for each of the following Value Adjustment Factors:"))
        self.label_4.setText(_translate("Dialog", "Does the system require reliable backup and recovery processes?"))
        self.label_3.setText(_translate("Dialog",
                                        "Are specialized data communications required to transfer information to and from the application?"))
        self.label_5.setText(_translate("Dialog", "Are there distributed processing functions?"))
        self.label_6.setText(_translate("Dialog", "Is performance critical?"))
        self.label_7.setText(
            _translate("Dialog", "Will the system run in an existing, heavily utilized operational environment?"))
        self.label_8.setText(_translate("Dialog", "Does the system require online data entry?"))
        self.label_10.setText(_translate("Dialog",
                                         "Does the online data entry require the input transaction to be built over multiple screens or operations?"))
        self.label_11.setText(_translate("Dialog", "Are the Internal Logical Files updated online?"))
        self.label_12.setText(_translate("Dialog", "Are the input, output, files, or inquires complex?"))
        self.label_13.setText(_translate("Dialog", "Is the internal processing complex?"))
        self.label_14.setText(_translate("Dialog", "Is the code designed to be reusable?"))
        self.label_15.setText(_translate("Dialog", "Are conversion and installation included in the design?"))
        self.label_9.setText(
            _translate("Dialog", "Is the system designed for multiple installations in different organizations?"))
        self.label_2.setText(
            _translate("Dialog", "Is the application desgined to facilitate change and for ease of use by the user?"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_2.activated[str].connect(self.calculate_vaf)
        self.comboBox_4.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_4.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_4.activated[str].connect(self.calculate_vaf)
        self.comboBox_5.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_5.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_5.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_5.activated[str].connect(self.calculate_vaf)
        self.comboBox_6.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_6.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_6.activated[str].connect(self.calculate_vaf)
        self.comboBox_8.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_8.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_8.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_8.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_8.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_8.activated[str].connect(self.calculate_vaf)
        self.comboBox_10.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_10.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_10.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_10.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_10.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_10.activated[str].connect(self.calculate_vaf)
        self.comboBox_13.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_13.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_13.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_13.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_13.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_13.activated[str].connect(self.calculate_vaf)
        self.comboBox_12.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_12.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_12.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_12.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_12.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_12.activated[str].connect(self.calculate_vaf)
        self.comboBox_9.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_9.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_9.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_9.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_9.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_9.activated[str].connect(self.calculate_vaf)
        self.comboBox_14.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_14.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_14.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_14.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_14.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_14.activated[str].connect(self.calculate_vaf)
        self.comboBox_11.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_11.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_11.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_11.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_11.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_11.activated[str].connect(self.calculate_vaf)
        self.comboBox_7.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_7.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_7.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_7.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_7.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_7.activated[str].connect(self.calculate_vaf)
        self.comboBox_3.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_3.activated[str].connect(self.calculate_vaf)
        self.comboBox.setItemText(0, _translate("Dialog", "1"))
        self.comboBox.setItemText(1, _translate("Dialog", "2"))
        self.comboBox.setItemText(2, _translate("Dialog", "3"))
        self.comboBox.setItemText(3, _translate("Dialog", "4"))
        self.comboBox.setItemText(4, _translate("Dialog", "5"))
        self.comboBox.activated[str].connect(self.calculate_vaf)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    ui.calculate_vaf()
    sys.exit(app.exec_())
