from PyQt5 import QtCore, QtGui, QtWidgets
import decimal

class Ui_Dialog(object):
    def __init__(self):
        self.result = 0.62

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(768, 526)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(320, 330, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(210, 320, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_41 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_41.setGeometry(QtCore.QRect(210, 360, 113, 20))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.label_69 = QtWidgets.QLabel(Dialog)
        self.label_69.setGeometry(QtCore.QRect(60, 360, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.label_68 = QtWidgets.QLabel(Dialog)
        self.label_68.setGeometry(QtCore.QRect(60, 320, 143, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 741, 241))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 8, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 4, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 7, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 5, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 6, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 7, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 3, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 6, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout.addWidget(self.label_46, 8, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 2, 4, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_13.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 4, 2, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 3, 2, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 3, 4, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 3, 3, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 4, 4, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 4, 3, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout.addWidget(self.lineEdit_15, 5, 3, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_16.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout.addWidget(self.lineEdit_16, 5, 2, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout.addWidget(self.lineEdit_14, 5, 4, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_19.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout.addWidget(self.lineEdit_19, 6, 2, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_21.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout.addWidget(self.lineEdit_21, 7, 3, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_20.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout.addWidget(self.lineEdit_20, 7, 4, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_18.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout.addWidget(self.lineEdit_18, 6, 3, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_17.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout.addWidget(self.lineEdit_17, 6, 4, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_22.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout.addWidget(self.lineEdit_22, 7, 2, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_23.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout.addWidget(self.lineEdit_23, 8, 4, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout.addWidget(self.lineEdit_24, 8, 3, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_25.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout.addWidget(self.lineEdit_25, 8, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 2, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 4, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 3, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 2, 3, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def calc_ECF(self):
        self.total_ECF = self.E1 = self.E2 = self.E3 = self.E4 = self.E5 = self.E6 = self.E7 = self.E8 = 0
        self.E1 += (float(self.lineEdit_2.text()) * float(self.lineEdit_3.text()))
        self.lineEdit_4.setText(str(self.E1))
        self.E2 += (float(self.lineEdit_5.text()) * float(self.lineEdit_6.text()))
        self.lineEdit_7.setText(str(self.E2))
        self.E3 += (float(self.lineEdit_10.text()) * float(self.lineEdit_8.text()))
        self.lineEdit_9.setText(str(self.E3))
        self.E4 += (float(self.lineEdit_13.text()) * float(self.lineEdit_11.text()))
        self.lineEdit_12.setText(str(self.E4))
        self.E5 += (float(self.lineEdit_16.text()) * float(self.lineEdit_15.text()))
        self.lineEdit_14.setText(str(self.E5))
        self.E6 += (float(self.lineEdit_19.text()) * float(self.lineEdit_18.text()))
        self.lineEdit_17.setText(str(self.E6))
        self.E7 += (float(self.lineEdit_22.text()) * float(self.lineEdit_21.text()))
        self.lineEdit_20.setText(str(self.E7))
        self.E8 += (float(self.lineEdit_25.text()) * float(self.lineEdit_24.text()))
        self.lineEdit_23.setText(str(self.E8))

        self.total_ECF = self.E1 + self.E2 + self.E3 + self.E4 + self.E5 + self.E6 + self.E7 + self.E8
        self.lineEdit.setText(str(self.total_ECF))
        # self.ECF = 1.4 + (-0.03 * self.total_ECF)
        self.ECF = round(decimal.Decimal(str(1.4 + (-0.03 * self.total_ECF))), 2)
        self.lineEdit_41.setText(str(self.ECF))
        self.set_ecf_value(self.ECF)

    def set_ecf_value(self, value):
            self.result = value

    def get_ecf_value(self):
            return self.result


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit.setText(_translate("Dialog", "26"))
        self.lineEdit_41.setText(_translate("Dialog", "0.62"))
        self.label_69.setText(_translate("Dialog", "ECF:"))
        self.label_68.setText(_translate("Dialog", "Total Environment Factor:"))
        self.label_42.setText(_translate("Dialog", "E8"))
        self.label_15.setText(_translate("Dialog", "Motivation"))
        self.label.setText(_translate("Dialog", "Factor"))
        self.label_21.setText(_translate("Dialog", "E4"))
        self.label_24.setText(_translate("Dialog", "E7"))
        self.label_22.setText(_translate("Dialog", "E5"))
        self.label_23.setText(_translate("Dialog", "E6"))
        self.label_19.setText(_translate("Dialog", "E2"))
        self.label_20.setText(_translate("Dialog", "E3"))
        self.label_18.setText(_translate("Dialog", "Part-time workers"))
        self.label_14.setText(_translate("Dialog", "Object Oriented Experience"))
        self.label_16.setText(_translate("Dialog", "Lead Analyst Capability"))
        self.label_17.setText(_translate("Dialog", "Stable Requirements"))
        self.label_46.setText(_translate("Dialog", "Difficult Programming Language"))
        self.lineEdit_7.setText(_translate("Dialog", "1"))
        self.lineEdit_13.setText(_translate("Dialog", "0.5"))
        self.lineEdit_10.setText(_translate("Dialog", "1"))
        self.lineEdit_9.setText(_translate("Dialog", "5"))
        self.lineEdit_8.setText(_translate("Dialog", "5"))
        self.lineEdit_12.setText(_translate("Dialog", "1"))
        self.lineEdit_11.setText(_translate("Dialog", "2"))
        self.lineEdit_15.setText(_translate("Dialog", "1"))
        self.lineEdit_16.setText(_translate("Dialog", "1"))
        self.lineEdit_14.setText(_translate("Dialog", "1"))
        self.lineEdit_19.setText(_translate("Dialog", "2"))
        self.lineEdit_21.setText(_translate("Dialog", "0 "))
        self.lineEdit_20.setText(_translate("Dialog", "0"))
        self.lineEdit_18.setText(_translate("Dialog", "5"))
        self.lineEdit_17.setText(_translate("Dialog", "10"))
        self.lineEdit_22.setText(_translate("Dialog", "0"))
        self.lineEdit_23.setText(_translate("Dialog", "2"))
        self.lineEdit_24.setText(_translate("Dialog", "1"))
        self.lineEdit_25.setText(_translate("Dialog", "2"))
        self.label_8.setText(_translate("Dialog", "Description"))
        self.label_12.setText(_translate("Dialog", "Impact"))
        self.label_10.setText(_translate("Dialog", "Weight"))
        self.label_11.setText(_translate("Dialog", "Rated Value"))
        self.label_2.setText(_translate("Dialog", "E1"))
        self.label_7.setText(_translate("Dialog", "Application Experience"))
        self.label_3.setText(_translate("Dialog", "Familiarity with UML"))
        self.lineEdit_5.setText(_translate("Dialog", "0.5"))
        self.lineEdit_4.setText(_translate("Dialog", "6"))
        self.lineEdit_2.setText(_translate("Dialog", "1.5"))
        self.lineEdit_3.setText(_translate("Dialog", "4"))
        self.lineEdit_6.setText(_translate("Dialog", "2"))
        #
        self.lineEdit_2.textChanged.connect(self.calc_ECF)
        self.lineEdit_3.textChanged.connect(self.calc_ECF)
        self.lineEdit_5.textChanged.connect(self.calc_ECF)
        self.lineEdit_6.textChanged.connect(self.calc_ECF)
        self.lineEdit_10.textChanged.connect(self.calc_ECF)
        self.lineEdit_8.textChanged.connect(self.calc_ECF)
        self.lineEdit_13.textChanged.connect(self.calc_ECF)
        self.lineEdit_11.textChanged.connect(self.calc_ECF)
        self.lineEdit_16.textChanged.connect(self.calc_ECF)
        self.lineEdit_15.textChanged.connect(self.calc_ECF)
        self.lineEdit_18.textChanged.connect(self.calc_ECF)
        self.lineEdit_19.textChanged.connect(self.calc_ECF)
        self.lineEdit_21.textChanged.connect(self.calc_ECF)
        self.lineEdit_22.textChanged.connect(self.calc_ECF)
        self.lineEdit_24.textChanged.connect(self.calc_ECF)
        self.lineEdit_25.textChanged.connect(self.calc_ECF)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
