from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from SelectLangPack import SE_select_language
from ValueAdjustmentFactors import SE_VAF


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 100, 521, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.EI_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.EI_lineedit.setMinimumSize(QtCore.QSize(100, 0))
        self.EI_lineedit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.EI_lineedit.setObjectName("EI_lineedit")
        self.horizontalLayout.addWidget(self.EI_lineedit)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 150, 521, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.EO_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.EO_lineedit.setMinimumSize(QtCore.QSize(100, 0))
        self.EO_lineedit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.EO_lineedit.setObjectName("EO_lineedit")
        self.horizontalLayout_2.addWidget(self.EO_lineedit)
        self.radioButton_4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_2.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_2.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_2.addWidget(self.radioButton_6)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 250, 521, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.ILF_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.ILF_lineedit.setMinimumSize(QtCore.QSize(100, 0))
        self.ILF_lineedit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ILF_lineedit.setObjectName("ILF_lineedit")
        self.horizontalLayout_3.addWidget(self.ILF_lineedit)
        self.radioButton_7 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_3.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_3.addWidget(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout_3.addWidget(self.radioButton_9)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 200, 521, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.EInq_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.EInq_lineedit.setMinimumSize(QtCore.QSize(100, 0))
        self.EInq_lineedit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.EInq_lineedit.setObjectName("EInq_lineedit")
        self.horizontalLayout_4.addWidget(self.EInq_lineedit)
        self.radioButton_10 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_10.setObjectName("radioButton_10")
        self.horizontalLayout_4.addWidget(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_11.setObjectName("radioButton_11")
        self.horizontalLayout_4.addWidget(self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_12.setObjectName("radioButton_12")
        self.horizontalLayout_4.addWidget(self.radioButton_12)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 300, 521, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.EIF_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.EIF_lineedit.setMinimumSize(QtCore.QSize(100, 0))
        self.EIF_lineedit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.EIF_lineedit.setObjectName("EIF_lineedit")
        self.horizontalLayout_5.addWidget(self.EIF_lineedit)
        self.radioButton_13 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.radioButton_13.setObjectName("radioButton_13")
        self.horizontalLayout_5.addWidget(self.radioButton_13)
        self.radioButton_14 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.radioButton_14.setObjectName("radioButton_14")
        self.horizontalLayout_5.addWidget(self.radioButton_14)
        self.radioButton_15 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.radioButton_15.setObjectName("radioButton_15")
        self.horizontalLayout_5.addWidget(self.radioButton_15)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 350, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 390, 201, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.computefp_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.computefp_btn.setObjectName("computefp_btn")
        self.verticalLayout.addWidget(self.computefp_btn)
        self.vaf_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.vaf_btn.setObjectName("vaf_btn")
        self.verticalLayout.addWidget(self.vaf_btn)
        self.codesize_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.codesize_btn.setObjectName("codesize_btn")
        self.verticalLayout.addWidget(self.codesize_btn)
        self.chooselang_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.chooselang_btn.setObjectName("chooselang_btn")
        self.verticalLayout.addWidget(self.chooselang_btn)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(320, 500, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(310, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(250, 70, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(360, 70, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(460, 70, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.EI_Label = QtWidgets.QLabel(self.centralwidget)
        self.EI_Label.setGeometry(QtCore.QRect(590, 110, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EI_Label.setFont(font)
        self.EI_Label.setObjectName("EI_Label")
        self.EO_Label = QtWidgets.QLabel(self.centralwidget)
        self.EO_Label.setGeometry(QtCore.QRect(590, 160, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EO_Label.setFont(font)
        self.EO_Label.setObjectName("EO_Label")
        self.EInq_Label = QtWidgets.QLabel(self.centralwidget)
        self.EInq_Label.setGeometry(QtCore.QRect(590, 210, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EInq_Label.setFont(font)
        self.EInq_Label.setObjectName("EInq_Label")
        self.ILF_Label = QtWidgets.QLabel(self.centralwidget)
        self.ILF_Label.setGeometry(QtCore.QRect(590, 260, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ILF_Label.setFont(font)
        self.ILF_Label.setObjectName("ILF_Label")
        self.EIF_Label = QtWidgets.QLabel(self.centralwidget)
        self.EIF_Label.setGeometry(QtCore.QRect(590, 310, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EIF_Label.setFont(font)
        self.EIF_Label.setObjectName("EIF_Label")
        self.TC_Label = QtWidgets.QLabel(self.centralwidget)
        self.TC_Label.setGeometry(QtCore.QRect(590, 350, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TC_Label.setFont(font)
        self.TC_Label.setObjectName("TC_Label")
        self.FP_Label = QtWidgets.QLabel(self.centralwidget)
        self.FP_Label.setGeometry(QtCore.QRect(590, 410, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FP_Label.setFont(font)
        self.FP_Label.setObjectName("FP_Label")
        self.VAF_Label = QtWidgets.QLabel(self.centralwidget)
        self.VAF_Label.setGeometry(QtCore.QRect(590, 450, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.VAF_Label.setFont(font)
        self.VAF_Label.setObjectName("VAF_Label")
        self.CodeSize_Label = QtWidgets.QLabel(self.centralwidget)
        self.CodeSize_Label.setGeometry(QtCore.QRect(590, 500, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CodeSize_Label.setFont(font)
        self.CodeSize_Label.setObjectName("CodeSize_Label")
        self.Language_Label = QtWidgets.QLabel(self.centralwidget)
        self.Language_Label.setGeometry(QtCore.QRect(450, 510, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Language_Label.setFont(font)
        self.Language_Label.setObjectName("Language_Label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 21))
        self.menubar.setObjectName("menubar")
        self.Menu_file = QtWidgets.QMenu(self.menubar)
        self.Menu_file.setObjectName("Menu_file")
        self.Menu_edit = QtWidgets.QMenu(self.menubar)
        self.Menu_edit.setObjectName("Menu_edit")
        self.Menu_preferences = QtWidgets.QMenu(self.menubar)
        self.Menu_preferences.setObjectName("Menu_preferences")
        self.Menu_metrics = QtWidgets.QMenu(self.menubar)
        self.Menu_metrics.setObjectName("Menu_metrics")
        self.menuFunction_Point = QtWidgets.QMenu(self.Menu_metrics)
        self.menuFunction_Point.setObjectName("menuFunction_Point")
        self.Menu_Project_code = QtWidgets.QMenu(self.menubar)
        self.Menu_Project_code.setObjectName("Menu_Project_code")
        self.Menu_Help = QtWidgets.QMenu(self.menubar)
        self.Menu_Help.setObjectName("Menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.File_new = QtWidgets.QAction(MainWindow)
        self.File_new.setObjectName("File_new")
        self.File_Open = QtWidgets.QAction(MainWindow)
        self.File_Open.setObjectName("File_Open")
        self.File_Save = QtWidgets.QAction(MainWindow)
        self.File_Save.setObjectName("File_Save")
        self.File_Exit = QtWidgets.QAction(MainWindow)
        self.File_Exit.setObjectName("File_Exit")
        self.actionEnter_FP_Data = QtWidgets.QAction(MainWindow)
        self.actionEnter_FP_Data.setObjectName("actionEnter_FP_Data")
        self.Menu_file.addAction(self.File_new)
        self.Menu_file.addAction(self.File_Open)
        self.Menu_file.addAction(self.File_Save)
        self.Menu_file.addAction(self.File_Exit)
        self.menuFunction_Point.addAction(self.actionEnter_FP_Data)
        self.Menu_metrics.addAction(self.menuFunction_Point.menuAction())
        self.menubar.addAction(self.Menu_file.menuAction())
        self.menubar.addAction(self.Menu_edit.menuAction())
        self.menubar.addAction(self.Menu_preferences.menuAction())
        self.menubar.addAction(self.Menu_metrics.menuAction())
        self.menubar.addAction(self.Menu_Project_code.menuAction())
        self.menubar.addAction(self.Menu_Help.menuAction())

        # comment start
        self.chooselang_btn.clicked.connect(self.displaylang)
        self.vaf_btn.clicked.connect(self.vafdialog)
        self.computefp_btn.clicked.connect(self.calculatefp)
        self.EI_lineedit.setText("0")
        self.EO_lineedit.setText("0")
        self.EInq_lineedit.setText("0")
        self.ILF_lineedit.setText("0")
        self.EIF_lineedit.setText("0")
        # comment end

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.calculatefp()

    def calculatefp(self):
        self.choice = 0
        self.ei = int(self.EI_lineedit.text())
        if self.radioButton.isChecked():
            self.choice = 3
        elif self.radioButton_3.isChecked():
            self.choice = 4
        elif self.radioButton_2.isChecked():
            self.choice = 6
        self.result = self.ei * self.choice
        self.EI_Label.setText(str(self.result))

        self.eo = int(self.EO_lineedit.text())
        if self.radioButton_4.isChecked():
            self.choice = 4
        elif self.radioButton_5.isChecked():
            self.choice = 5
        elif self.radioButton_6.isChecked():
            self.choice = 7
        self.result = self.eo * self.choice
        self.EO_Label.setText(str(self.result))

        self.einq = int(self.EInq_lineedit.text())
        if self.radioButton_10.isChecked():
            self.choice = 3
        elif self.radioButton_11.isChecked():
            self.choice = 4
        elif self.radioButton_12.isChecked():
            self.choice = 6
        self.result = self.einq * self.choice
        self.EInq_Label.setText(str(self.result))

        self.ilf = int(self.ILF_lineedit.text())
        if self.radioButton_7.isChecked():
            self.choice = 7
        elif self.radioButton_8.isChecked():
            self.choice = 10
        elif self.radioButton_9.isChecked():
            self.choice = 15
        self.result = self.ilf * self.choice
        self.ILF_Label.setText(str(self.result))

        self.eif = int(self.EIF_lineedit.text())
        if self.radioButton_13.isChecked():
            self.choice = 5
        elif self.radioButton_14.isChecked():
            self.choice = 7
        elif self.radioButton_15.isChecked():
            self.choice = 10
        self.result = self.eif * self.choice
        self.EIF_Label.setText(str(self.result))

        # ********************
        self.totalcount = int(self.EI_Label.text()) + int(self.EO_Label.text()) + int(self.EInq_Label.text()) + int(self.ILF_Label.text()) + int(self.EIF_Label.text())
        self.TC_Label.setText(str(self.totalcount))
        self.fp = self.totalcount * (0.65 + (0.01 * 20))
        self.FP_Label.setText(str(self.fp))
        # *********************

    def displaylang(self):
        self.Dialog = QtWidgets.QDialog()
        self.lang_obj = SE_select_language.Ui_Dialog()
        self.lang_obj.setupUi(self.Dialog)
        self.Dialog.show()

    def vafdialog(self):
        self.Dialog = QtWidgets.QDialog()
        self.vaf_obj = SE_VAF.Ui_Dialog()
        self.vaf_obj.setupUi(self.Dialog)
        self.Dialog.show()
        self.response = self.Dialog.exec_()

        if self.response == QtWidgets.QDialog.Accepted:
            self.VAF_Label.setText(str(self.vaf_obj.get_vaf_value()))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Function Points"))
        self.label.setText(_translate("MainWindow", "External Inputs"))
        self.radioButton.setText(_translate("MainWindow", "3"))
        self.radioButton_3.setText(_translate("MainWindow", "4"))
        self.radioButton_3.setChecked(True)
        self.radioButton_2.setText(_translate("MainWindow", "6"))
        self.label_2.setText(_translate("MainWindow", "External Outputs"))
        self.radioButton_4.setText(_translate("MainWindow", "4"))
        self.radioButton_5.setText(_translate("MainWindow", "5"))
        self.radioButton_5.setChecked(True)
        self.radioButton_6.setText(_translate("MainWindow", "7"))
        self.label_3.setText(_translate("MainWindow", "Internal Logic Files"))
        self.radioButton_7.setText(_translate("MainWindow", "7"))
        self.radioButton_8.setText(_translate("MainWindow", "10"))
        self.radioButton_8.setChecked(True)
        self.radioButton_9.setText(_translate("MainWindow", "15"))
        self.label_4.setText(_translate("MainWindow", "External Inquiries"))
        self.radioButton_10.setText(_translate("MainWindow", "3"))
        self.radioButton_11.setText(_translate("MainWindow", "4"))
        self.radioButton_11.setChecked(True)
        self.radioButton_12.setText(_translate("MainWindow", "6"))
        self.label_5.setText(_translate("MainWindow", "Ext Interface Files"))
        self.radioButton_13.setText(_translate("MainWindow", "5"))
        self.radioButton_14.setText(_translate("MainWindow", "7"))
        self.radioButton_14.setChecked(True)
        self.radioButton_15.setText(_translate("MainWindow", "10"))
        self.label_6.setText(_translate("MainWindow", "Total Count"))
        self.computefp_btn.setText(_translate("MainWindow", "Compute FP"))
        self.vaf_btn.setText(_translate("MainWindow", "Value Adjustments"))
        self.codesize_btn.setText(_translate("MainWindow", "Compute Code Size"))
        self.chooselang_btn.setText(_translate("MainWindow", "Choose Language"))
        self.label_7.setText(_translate("MainWindow", "Current Language"))
        self.label_8.setText(_translate("MainWindow", "Weighting Factors"))
        self.label_9.setText(_translate("MainWindow", "Simple"))
        self.label_10.setText(_translate("MainWindow", "Average"))
        self.label_11.setText(_translate("MainWindow", "Complex"))
        self.EI_Label.setText(_translate("MainWindow", "0"))
        self.EO_Label.setText(_translate("MainWindow", "0"))
        self.EInq_Label.setText(_translate("MainWindow", "0"))
        self.ILF_Label.setText(_translate("MainWindow", "0"))
        self.EIF_Label.setText(_translate("MainWindow", "0"))
        self.TC_Label.setText(_translate("MainWindow", "0"))
        self.FP_Label.setText(_translate("MainWindow", "0"))
        self.VAF_Label.setText(_translate("MainWindow", "0"))
        self.CodeSize_Label.setText(_translate("MainWindow", "0"))
        self.Language_Label.setText(_translate("MainWindow", "Python"))
        self.Menu_file.setTitle(_translate("MainWindow", "File"))
        self.Menu_edit.setTitle(_translate("MainWindow", "Edit"))
        self.Menu_preferences.setTitle(_translate("MainWindow", "Preferences"))
        self.Menu_metrics.setTitle(_translate("MainWindow", "Metrics"))
        self.menuFunction_Point.setTitle(_translate("MainWindow", "Function Point"))
        self.Menu_Project_code.setTitle(_translate("MainWindow", "Project code"))
        self.Menu_Help.setTitle(_translate("MainWindow", "Help"))
        self.File_new.setText(_translate("MainWindow", "New"))
        self.File_new.setStatusTip(_translate("MainWindow", "Create a new file"))
        self.File_new.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.File_Open.setText(_translate("MainWindow", "Open"))
        self.File_Save.setText(_translate("MainWindow", "Save"))
        self.File_Save.setStatusTip(_translate("MainWindow", "Save the file"))
        self.File_Save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.File_Exit.setText(_translate("MainWindow", "Exit"))
        self.actionEnter_FP_Data.setText(_translate("MainWindow", "Enter FP Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
